[tool.poetry]
name = "opticc-tool"
version = "0.0.1"
description = "OPTICC TOOL"
authors = [
  "Memory Kumbikano <mkumbikano@redcross.nl>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
